version: "3"

services:
  mysql:
    image: mysql:5.6
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test"
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    networks:
      - private
  web:
    build: ../
    depends_on:
      - mysql
    ports: 
      - "80:8080"
    image: node_app
    networks:
      - private
  webTest:
    build: ../
    depends_on:
      - mysql
    ports: 
      - "8080:8080"
    image: node_app
    networks:
      - private
    command: npm test
networks:
  private: