version: "3"

services: 
  #build: ../Dockerfile
  #build: ../
  web:
    build: ../
    ports:
      - "80:8080"
    networks:
      - private
  #command: npm
  
  #volumes:
      #- .:/usr/app/
      #- /usr/app/node_modules
  
  mysql:
    image: mysql:5.6
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - private
networks: 
  private: