version: "3"

services:
  api:
    build: ../
    ports:
      - "80:8080"
    networks:
      - private
  test:
    build: ../
    command: "npm test"
    networks:
      - private
  
networks:
  private:
