version: "3"

networks:
  private:
    driver : bridge

services:
  mysql:
    image: mysql:5.6
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test"
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    networks:
      - private
  worker:
    build: ../
    depends_on:
      - mysql
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - private
  workertest:
    build: ../
    depends_on:
      - mysql
     expose:
      - 8080
    ports:
      - 8080:8080
    command: 
      - npm test
    networks:
      - private
      
