version: "3"

networks:
  private:
    driver : bridge

services:
  mysql:
    image: mysql:5.6
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - private
  worker:
    image: myimage:1.0
    ports:
      - "8080:8080"
    networks:
      - private
