version: "3"

services:
  node_app:
    ports:
      - "80:8080"
    build: 
      context: ../
      dockerfile: Dockerfile
    image: node_app
    networks:
      - private
  tester:
    build: ../
    command: npm test
    networks:
      - private
networks:
  private:
    
