version: "3"

services:
  mysql:
    image: mysql:5.6
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test"
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    networks:
      - private
  node_app:
    depends_on:
      - mysql
    ports:
      - "80:8080"
    build: 
      context: ../
      dockerfile: Dockerfile
    image: node_app
    networks:
      - private
  tester:
    build: ../
    depends_on:
      - mysql
    command: npm test
    networks:
      - private
networks:
  private:
    
