version: "3"

services:
  app:
    build: ../
    depends_on:
    - mysql
    expose:
      - 8080
    ports:
      - "80:8080"
    networks:
      - private
  
  mysql:
    image: mysql:5.6
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test"
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
    networks: 
      - private
      
networks:
  private: