version: "3"

networks:
  private:

services:
      
  node_app:
    build: ../
    ports:
    - 80:8080
    networks:
    - private
    
  test:
    build: ../
    command: ["npm", "test"]
    networks:
    - private