version: "3"

services:
  mysql:
    image: mysql:5.6
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - private
  node_app:
    build: 
      context: ../
      dockerfile: Dockerfile
    image: node_app
    networks:
      - private
    
networks:
  private:
    
